server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/green?serverTimezone=Asia/Seoul&charatorEncoding=UTF-8
    username: root
    password: 1234
  thymeleaf:
    cache: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
